version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5003:5000
    volumes:
      - '.:/app'
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevConfig
      - SECRET_KEY=supersecretdevonlykey
      - SVG_MONITORING_BASE_URI=http://svg_monitoring:5001
      - SVG_AUTH_BASE_URI=http://svg_auth:5000
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    networks:
      - svg_shared
networks:
  svg_shared:
    external:
      name: svg_shared
