version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5003:5000
    volumes:
      - '.:/app'
    external_links:
      - svg_gateway_app_1:svg_gateway
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevConfig
      - SECRET_KEY=supersecretdevonlykey
      - SVG_GATEWAY_URI=http://svg_gateway:5000
    env_file:
    - project/.env
    networks:
      - svg_shared
networks:
  svg_shared:
    external:
      name: svg_shared
